# Generated by Django 4.0.4 on 2022-04-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='location_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='user.location'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='product.category'),
        ),
    ]
